/* Execute the real shell/detail routing with a small DOM fixture; not a browser audit. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../dist/app.js'),'utf8');
let document,htmlWrites=0;
const decode=s=>String(s).replaceAll('&quot;','"').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&');
class Node{
 constructor(tag='div',attrs={}){this.tagName=tag;this.attrs={...attrs};this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.children=[];this.parentNode=null;this.listeners={};this.hidden='hidden'in attrs;this.open='open'in attrs;this.scrollLeft=0;this.scrollTop=0;this.style={setProperty(){}};this.value=attrs.value||'';this.type=attrs.type||'';this.text='';this.writes=0;this.classList={contains:c=>(this.attrs.class||'').split(/\s+/).includes(c),toggle:(c,on)=>{const values=new Set((this.attrs.class||'').split(/\s+/).filter(Boolean));if(on??!values.has(c))values.add(c);else values.delete(c);this.attrs.class=[...values].join(' ');},add:c=>this.classList.toggle(c,true),remove:c=>this.classList.toggle(c,false)};}
 get id(){return this.attrs.id;}getAttribute(k){return this.attrs[k]??null;}setAttribute(k,v){this.attrs[k]=String(v);}removeAttribute(k){delete this.attrs[k];}
 append(child){child.parentNode=this;this.children.push(child);}
 get innerHTML(){return this.children.map(x=>x.tagName==='#text'?x.text:`<${x.tagName}${Object.entries(x.attrs).map(([k,v])=>` ${k}="${v}"`).join('')}>${x.innerHTML}</${x.tagName}>`).join('');}
 set innerHTML(html){this.writes++;htmlWrites++;this.children=[];const stack=[this],voids=new Set(['input','img','br','hr','meta','link']);for(const chunk of String(html).match(/<[^>]+>|[^<]+/g)||[]){if(chunk.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(chunk.startsWith('<')){const match=chunk.match(/^<([\w-]+)([\s\S]*?)\/?>(?:$)/);if(!match)continue;const attrs={};for(const a of match[2].matchAll(/([\w:-]+)(?:="([^"]*)")?/g))attrs[a[1]]=decode(a[2]||'');const child=new Node(match[1],attrs);stack.at(-1).append(child);if(!voids.has(match[1])&&!chunk.endsWith('/>'))stack.push(child);}else{const child=new Node('#text');child.text=chunk;stack.at(-1).append(child);}}}
 get textContent(){return this.tagName==='#text'?decode(this.text):this.children.map(c=>c.textContent).join('');}set textContent(value){this.children=[];const child=new Node('#text');child.text=String(value);this.append(child);}
 matches(selector){if(selector.startsWith('#'))return this.id===selector.slice(1);if(selector.startsWith('.'))return this.classList.contains(selector.slice(1));const attr=selector.match(/^\[([\w-]+)(?:="([^"]*)")?\]$/);if(attr)return attr[1]in this.attrs&&(attr[2]===undefined||this.attrs[attr[1]]===attr[2]);return this.tagName===selector;}
 querySelectorAll(selector){const parts=selector.trim().split(/\s+/),out=[];const walk=node=>{for(const child of node.children){if(child.matches(parts.at(-1))){let parent=child.parentNode,index=parts.length-2;while(index>=0&&parent){if(parent.matches(parts[index]))index--;parent=parent.parentNode;}if(index<0)out.push(child);}walk(child);}};walk(this);return out;}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}focus(){document.activeElement=this;}getBoundingClientRect(){return {top:this.top??120};}
}
const main=new Node('main'),nav=new Node('nav'),search=new Node('input'),crumbs=new Node('div'),root=new Node('div');for(const [id,node]of [['content',main],['navigation',nav],['search',search],['breadcrumbs',crumbs]]){node.setAttribute('id',id);root.append(node);}document={activeElement:null,title:'',querySelector:s=>root.querySelector(s),getElementById:id=>root.querySelector('#'+id)};
const items=[['button','Button','Atoms'],['accordion','Accordion','Molecules'],['colors','Colors','Foundations'],['semantic-tokens','Semantic tokens','Foundations'],['borders','Borders','Foundations']].map(([id,name,group])=>({id,name,group,sections:group==='Foundations'?[]:[['Overview','overview'],['Types','types'],['Sizes','sizes']],controls:group==='Foundations'?[]:[{key:'variant',type:'select',options:['primary','secondary'],default:'primary',label:'Type'},{key:'size',type:'select',options:['sm','md'],default:'md',label:'Size'}],tokens:[]}));
const F={current:null,config:{},groups:['Foundations','Atoms','Molecules'],byId:Object.fromEntries(items.map(i=>[i.id,i])),visibleItems:()=>items,matchesSearch:(item,q)=>item.name.toLowerCase().includes(q),defaults:item=>Object.fromEntries(item.controls.map(c=>[c.key,c.default])),escape:decode,componentParts:()=>[],componentTokens:()=>[],tokenTable:()=>'',controlLabel:(item,ctl)=>ctl.label,preview:(item,c)=>`<button>${item.name} ${c.variant} ${c.size}</button>`,clearCovers(){},mountCovers(){},clearPreviews(){this.cleared=(this.cleared||0)+1;},wirePreview(){this.wired=(this.wired||0)+1;},enhanceSelects:()=>()=>{},copy(){},tokens:{}};
F.palettes={blue:{500:'#2563eb'}};F.tokens={'color.blue.500':{},'semantic.text.body':{}};F.v=id=>'var(--'+id+')';
F.migrateRoute=(id,section,query)=>({id:!id?'all':id,section,query});
let rafId=0;const frames=new Map,scrolls=[],renders=[],location={hash:'#button/overview'},history={replaceState(state,title,url){location.hash=url;}};
const windowEvents={};const view={scrollY:230,innerHeight:800,scrollTo(...args){scrolls.push(args);this.scrollY=typeof args[0]==='object'?args[0].top:args[1];},addEventListener(type,fn){(windowEvents[type]??=[]).push(fn);}};
const context={F,document,window:view,location,history,URLSearchParams,main,nav,search,I:()=>'<svg></svg>',E:decode,requestAnimationFrame:fn=>{frames.set(++rafId,fn);return rafId;},cancelAnimationFrame:id=>frames.delete(id)};vm.createContext(context);
vm.runInContext("let category='All',searchTerm='',routeSection='overview',routeFrame=0,navigationSearch=null;const navigationGroups=new Map(),navigationSections=new Map();const titleCase=s=>s;function setMenuOpen(){}\n"+source.slice(source.indexOf('function iconFor('),source.indexOf("window.addEventListener('hashchange'")),context);
vm.runInContext(source.slice(source.indexOf("window.addEventListener('hashchange'"),source.indexOf("document.querySelector('.skip')")),context);
const run=code=>vm.runInContext(code,context),flush=()=>{const pending=[...frames.values()];frames.clear();pending.forEach(fn=>fn());};
run('route()');assert.equal(F.current.id,'button');assert.equal(scrolls.at(-1)[0].top,0);const tabs=main.querySelector('.detail-tabs'),body=main.querySelector('#detail-body'),typeLink=tabs.querySelectorAll('a')[1];tabs.scrollLeft=145;tabs.top=120;typeLink.focus();nav.scrollTop=310;
// User disclosure choices survive both same-family tabs and another family.
nav.querySelector('[data-nav-group="Foundations"]').open=false;nav.querySelector('[data-nav-group="Molecules"]').open=true;
const buttonSections=document.getElementById('nav-button');buttonSections.hidden=true;const navWrites=nav.writes,mainWrites=main.writes,cleared=F.cleared;
scrolls.length=0;view.scrollY=230;location.hash='#button/types';run('scheduleRoute()');flush();
assert.equal(main.querySelector('.detail-tabs'),tabs,'Tab row must retain identity');assert.equal(main.querySelector('#detail-body'),body,'Only the section body is replaced');assert.equal(document.activeElement,typeLink,'Focused tab must survive');assert.equal(tabs.scrollLeft,145);assert.equal(nav.scrollTop,310);assert.equal(nav.writes,navWrites);assert.equal(main.writes,mainWrites);assert.equal(scrolls.length,0,'Visible tabs must not reset document scroll');assert.equal(F.cleared,cleared+1,'Replaced previews clean up once');assert.equal(typeLink.getAttribute('aria-current'),'page');assert.equal(buttonSections.hidden,true,'Manual collapse survives same-family navigation');assert.equal(nav.querySelector('[data-nav-group="Foundations"]').open,false);
// Rapid changes render the latest route only; obsolete frame callbacks do not mount.
const writesBefore=body.writes;location.hash='#button/sizes';run('scheduleRoute()');location.hash='#button/types';run('scheduleRoute()');assert.equal(frames.size,1);flush();assert.equal(body.writes,writesBefore+1);assert.match(body.innerHTML,/2 variations/);assert.equal(typeLink.getAttribute('aria-current'),'page');
// Direct navigation cancels pending hash work, and offscreen tabs come into view instantly.
location.hash='#button/sizes';run('scheduleRoute()');tabs.top=-450;view.scrollY=700;run('route()');assert.equal(frames.size,0);assert.equal(scrolls.at(-1)[0].top,234);assert.equal(scrolls.at(-1)[0].behavior,'instant');
// Family navigation scrolls to the new heading but retains sidebar choices and scroll.
location.hash='#accordion/overview';run('route()');assert.equal(F.current.id,'accordion');assert.equal(scrolls.at(-1)[0].top,0);assert.equal(nav.scrollTop,310);assert.equal(nav.writes,navWrites);assert.equal(nav.querySelector('[data-nav-group="Foundations"]').open,false);assert.equal(nav.querySelector('[data-nav-group="Molecules"]').open,true);assert.equal(document.getElementById('nav-accordion').hidden,false);assert.equal(buttonSections.hidden,true);
// Back/forward-style hash changes restore the actual prior routes and configurations.
const beforeOverviewCleanup=F.cleared;location.hash='#button/overview?variant=secondary';run('scheduleRoute()');flush();assert.equal(F.cleared,beforeOverviewCleanup+1,'Overview also cleans outgoing previews only once');assert.equal(F.current.id,'button');assert.equal(F.config.variant,'secondary');location.hash='#accordion/types';run('scheduleRoute()');flush();assert.equal(F.current.id,'accordion');assert.match(main.querySelector('#detail-body').innerHTML,/2 variations/);
// Category tabs keep their focus and horizontal position while replacing only covers.
location.hash='#all';run('route()');const categoryTabs=main.querySelector('.category-tabs'),atomCategory=main.querySelectorAll('[data-category]').find(n=>n.dataset.category==='Atoms');categoryTabs.scrollLeft=96;atomCategory.focus();const catalogueBody=main.querySelector('#catalogue-body'),catalogueMainWrites=main.writes;atomCategory.onclick();assert.equal(main.writes,catalogueMainWrites);assert.equal(main.querySelector('.category-tabs'),categoryTabs);assert.equal(main.querySelector('#catalogue-body'),catalogueBody);assert.equal(categoryTabs.scrollLeft,96);assert.equal(document.activeElement,atomCategory);assert.equal(atomCategory.getAttribute('aria-pressed'),'true');assert.match(catalogueBody.innerHTML,/Button/);assert.doesNotMatch(catalogueBody.innerHTML,/Accordion/);
// Filtering may rebuild the sidebar, but clearing it restores user-set group state.
nav.querySelector('[data-nav-group="Atoms"]').open=false;run("searchTerm='button';renderCatalogue()");run("searchTerm='';renderCatalogue()");assert.equal(nav.querySelector('[data-nav-group="Atoms"]').open,false,'Search expansion must remain temporary');assert.equal(nav.querySelector('[data-nav-group="Foundations"]').open,false,'Search must not erase collapsed group preference');
// The color foundations form one tab cohort despite their distinct canonical IDs.
location.hash='#colors';run('route()');const foundationTabs=main.querySelector('.foundation-tabs'),foundationBody=main.querySelector('#foundation-body'),semanticTab=foundationTabs.querySelectorAll('a')[1],paletteTab=foundationTabs.querySelectorAll('a')[0];foundationTabs.top=140;foundationTabs.scrollLeft=74;semanticTab.focus();const foundationMainWrites=main.writes;scrolls.length=0;view.scrollY=160;location.hash='#semantic-tokens';windowEvents.hashchange.forEach(fn=>fn());flush();assert.equal(main.writes,foundationMainWrites,'Foundation pair does not replace main');assert.equal(main.querySelector('.foundation-tabs'),foundationTabs);assert.equal(main.querySelector('#foundation-body'),foundationBody);assert.equal(document.activeElement,semanticTab);assert.equal(foundationTabs.scrollLeft,74);assert.equal(scrolls.length,0,'Visible foundation tabs do not reset scroll');assert.equal(semanticTab.getAttribute('aria-current'),'page');assert.equal(main.querySelector('.page-heading h1').textContent,'Semantic tokens');assert.equal(F.current.id,'semantic-tokens');assert.match(crumbs.innerHTML,/Semantic tokens/);
// Back to Primitives keeps the same row; moving to an unrelated foundation resets normally.
paletteTab.focus();location.hash='#colors';windowEvents.hashchange.forEach(fn=>fn());flush();assert.equal(main.querySelector('.foundation-tabs'),foundationTabs);assert.equal(document.activeElement,paletteTab);assert.equal(paletteTab.getAttribute('aria-current'),'page');assert.match(foundationBody.innerHTML,/palette-blue/);assert.equal(main.querySelector('.page-heading h1').textContent,'Colors');location.hash='#borders';run('route()');assert.equal(main.querySelector('.foundation-tabs'),null);assert.equal(scrolls.at(-1)[0].top,0);
// Leaving the document cancels scheduled work; BFCache restoration rechecks the current hash.
location.hash='#colors';run('scheduleRoute()');assert.equal(frames.size,1);windowEvents.pagehide.forEach(fn=>fn());assert.equal(frames.size,0);assert.equal(F.current.id,'borders');windowEvents.pageshow.forEach(fn=>fn({persisted:true}));assert.equal(frames.size,1);flush();assert.equal(F.current.id,'colors');
const css=fs.readFileSync(path.join(__dirname,'../dist/styles.css'),'utf8');assert.match(css,/html\{scrollbar-gutter:stable\}/);assert.doesNotMatch(source.slice(source.indexOf('function route(){'),source.indexOf("document.querySelector('.skip')")),/behavior:'smooth'|setTimeout/);
console.log(JSON.stringify({checks:'tab/header identity, focus, horizontal and sidebar scroll, disclosure preferences, one cleanup, rapid route coalescing/cancellation, new page position, back/forward hashes, category tabs, search restoration, color foundation cohort, page lifecycle cancellation',sameFamilyShellRebuilds:0,sameFamilyVisibleTabScrollResets:0,status:'passed',scope:'Actual routing/render functions with DOM fixtures; no browser appearance claim'}));
