/* Simulated DOM and SpeechRecognition contracts; no browser/microphone session. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const dist=path.join(__dirname,'../dist');let document;
const decode=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
class Node{
 constructor(attrs={},tag='div'){this.attrs={};this.tag=tag;this.nodeType=tag==='#text'?3:1;this.nodeName=tag.toUpperCase();this.tagName=this.nodeName;this.dataset={};this.events={};this.children=[];this.style={};this.value='';this.hidden=false;this.disabled=false;this.scrollHeight=40;this._text='';for(const [k,v]of Object.entries(attrs))this.setAttribute(k,v);}
 get childNodes(){return this.children;}get parentNode(){return this.parent||null;}get firstChild(){return this.children[0]||null;}get ownerDocument(){return document;}
 get textContent(){return this.nodeType===3?this._text:this.children.map(n=>n.textContent).join('');}set textContent(value){if(this.nodeType===3)this._text=String(value);else{this.replaceChildren();if(value)this.append(text(String(value)));}}
 addEventListener(type,fn){(this.events[type]??=[]).push(fn);}removeEventListener(type,fn){this.events[type]=(this.events[type]||[]).filter(x=>x!==fn);}
 fire(type,props={}){const event={type,target:this,preventDefault(){this.defaultPrevented=true;},stopPropagation(){},...props};for(const fn of this.events[type]||[])fn(event);return event;}
 setAttribute(key,value){this.attrs[key]=String(value);if(key.startsWith('data-'))this.dataset[key.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=String(value);}getAttribute(key){return this.attrs[key]??null;}removeAttribute(key){delete this.attrs[key];}
 append(...nodes){for(const node of nodes){node.remove();this.children.push(node);node.parent=this;}}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null;}
 replaceWith(node){if(!this.parent)return;const parent=this.parent,index=parent.children.indexOf(this);node.remove();parent.children[index]=node;node.parent=parent;this.parent=null;}
 replaceChildren(...nodes){for(const child of this.children)child.parent=null;this.children=[];this.markup='';this.append(...nodes);}
 contains(node){return this===node||this.children.some(child=>child.contains(node));}
 matches(selector){if(selector==='.pp-prompt-tag')return this.attrs.class==='pp-prompt-tag';const m=selector.match(/^(\w+)?(?:\[([^\]]+)\])?$/);return !!m&&(!m[1]||m[1]===this.tag)&&(!m[2]||m[2]in this.attrs);}
 closest(selector){return this.matches(selector)?this:this.parent?.closest(selector)||null;}
 querySelectorAll(selector){return this.children.flatMap(child=>[...(child.matches(selector)?[child]:[]),...child.querySelectorAll(selector)]);}querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 focus(){document.activeElement=this;}showPopover(){this.opened=true;}hidePopover(){this.opened=false;}getBoundingClientRect(){return {left:60,right:140,top:100,bottom:132,width:80,height:32};}
 set innerHTML(markup){this.markup=markup;this.replaceChildren();this.markup=markup;
  const mention=markup.match(/^<span class="[^"]+" data-prompt-mention="([^"]+)" data-prompt-value="([^"]+)"/);
  if(mention){const atom=new Node({'data-prompt-mention':mention[1],'data-prompt-value':decode(mention[2]),contenteditable:'false'});atom.textContent=decode(mention[2]);this.append(atom);return;}
  for(const match of markup.matchAll(/<button\b([^>]+)>/g)){const action=match[1].match(/data-prompt-action="([^"]+)"/);if(!action)continue;const attrs={'data-prompt-action':action[1]};for(const key of ['value','kind']){const found=match[1].match(new RegExp('data-prompt-'+key+'="([^"]+)"'));if(found)attrs['data-prompt-'+key]=decode(found[1]);}this.append(new Node(attrs,'button'));}
  if(markup.includes('data-prompt-search'))this.append(new Node({'data-prompt-search':''},'input'));if(markup.includes('data-prompt-results'))this.append(new Node({'data-prompt-results':''}));
 }get innerHTML(){return this.markup||'';}
 insertAdjacentHTML(_,markup){this.markup=(this.markup||'')+markup;const tag=new Node({class:'pp-prompt-tag'}),remove=new Node({'data-prompt-remove':'files'},'button');tag.append(remove);this.append(tag);}
}
const text=value=>{const node=new Node({},'#text');node.textContent=value;return node;};
const plain=node=>node.dataset?.promptMention?node.dataset.promptValue:node.nodeType===3?node.textContent:node.children.map(plain).join('');
const rootOf=node=>{while(node.parent&&!node.parent.matches('[data-prompt-input]'))node=node.parent;return node.parent||node;};
const offsetOf=(root,node,offset)=>node===root?root.children.slice(0,offset).reduce((n,c)=>n+plain(c).length,0):root.children.slice(0,root.children.indexOf(node)).reduce((n,c)=>n+plain(c).length,0)+offset;
const boundary=(root,offset)=>{let consumed=0;for(let i=0;i<root.children.length;i++){const n=root.children[i],len=plain(n).length;if(offset===consumed)return i;if(offset<consumed+len){assert.equal(n.nodeType,3,'Range never splits an atomic mention');const a=text(n.textContent.slice(0,offset-consumed)),b=text(n.textContent.slice(offset-consumed));root.children.splice(i,1,a,b);a.parent=b.parent=root;n.parent=null;return i+1;}consumed+=len;}return root.children.length;};
class Range{
 setStart(node,offset){this.startContainer=node;this.startOffset=offset;}setEnd(node,offset){this.endContainer=node;this.endOffset=offset;}collapse(){this.setEnd(this.startContainer,this.startOffset);}setStartAfter(node){this.setStart(node.parent,node.parent.children.indexOf(node)+1);}
 deleteContents(){const root=this.startContainer.matches?.('[data-prompt-input]')?this.startContainer:rootOf(this.startContainer),start=offsetOf(root,this.startContainer,this.startOffset),end=offsetOf(root,this.endContainer,this.endOffset);boundary(root,end);const a=boundary(root,start),b=boundary(root,end);for(const n of root.children.splice(a,b-a))n.parent=null;this.setStart(root,a);this.collapse();}
 insertNode(node){const root=this.startContainer.matches?.('[data-prompt-input]')?this.startContainer:rootOf(this.startContainer),index=boundary(root,offsetOf(root,this.startContainer,this.startOffset));node.remove();root.children.splice(index,0,node);node.parent=root;}
}
const window=new Node();document=new Node();document.body=new Node();document.head={append(){}};document.createElement=tag=>new Node({},tag);document.createTextNode=text;document.createRange=()=>new Range();document.getElementById=()=>new Node();document.defaultView=window;window.innerWidth=900;window.innerHeight=700;
const selection={ranges:[],get rangeCount(){return this.ranges.length;},getRangeAt(){return this.ranges[0];},removeAllRanges(){this.ranges=[];},addRange(range){this.ranges=[range];}};window.getSelection=()=>selection;
const context={window,document};vm.createContext(context);for(const file of ['tokens.js','hugeicons-icons.js','tag.js','utility-atoms.js','navigation-controls.js','drawer.js','menus.js','prompt-bar.js','previews.js'])vm.runInContext(fs.readFileSync(path.join(dist,file),'utf8'),context,{filename:file});
const F=window.Forma,css=fs.readFileSync(path.join(dist,'prompt-bar.css'),'utf8');let configurations=0,contracts=0;
for(const variant of ['home','conversation'])for(const state of ['default','pending','disabled'])for(const mode of ['none','web','research','thinking'])for(const attachments of ['none','files','voice'])for(const mention of ['none','company','list','both']){
 const c={variant,state,mode,attachments,mention,value:'<img onerror="bad">'},html=F.promptBar(c);
 assert.match(html,/&lt;img onerror=&quot;bad&quot;&gt;/);assert.match(html,/role="textbox" contenteditable=/);assert.match(html,/aria-multiline="true" aria-required="true"/);assert.match(html,/<input type="hidden" name="prompt"/);
 assert.equal((html.match(/data-prompt-remove="files"/g)||[]).length,attachments==='files'?2:0);assert.doesNotMatch(html,/Voice note|data-prompt-remove="voice"/);
 assert.equal((html.match(/data-prompt-mention="company"/g)||[]).length,['company','both'].includes(mention)?1:0);assert.equal((html.match(/data-prompt-mention="list"/g)||[]).length,['list','both'].includes(mention)?1:0);
 assert.equal(html.includes('pp-prompt-mode-tag'),mode!=='none');assert.equal(html.match(/<button[^>]*data-prompt-send[^>]*>/)[0].includes(' disabled'),state!=='default');assert.equal(html.includes('contenteditable="true"'),state!=='disabled');assert.doesNotMatch(html,/<input[^>]+type="file"|<audio|autoplay|onclick=/);
 for(const id of F.promptBarTokens(c)){assert.notEqual(F.resolve(id),undefined,id);if(id.startsWith('component.prompt.'))assert.match(F.tokens[id].value,/^\{.+\}$/);}configurations++;
}
for(const [role,value]of Object.entries({minHeight:'112px',radius:'20px',padding:'12px',font:'15px',line:'24px','control.size':'32px','control.radius':'10px','send.size':'40px','send.radius':'12px','send.icon':'17px','list.radius':'8px','list.icon':'14px','mention.weight':500}))assert.equal(F.resolve('component.prompt.'+role),value);
assert.equal(F.tokens['semantic.prompt.mention.foreground'].value,'{color.blue.500}');for(const [,variable]of css.matchAll(/var\((--pp-[\w-]+)/g))assert.ok(Object.keys(F.tokens).some(id=>F.varName(id)===variable),variable);assert.match(css,/@media\(forced-colors:active\)/);
const test=run=>{run();contracts++;};
function fixture(state='default'){
 selection.removeAllRanges();const root=new Node(),form=new Node({'data-prompt-bar':''},'form'),input=new Node({'data-prompt-input':'',contenteditable:state==='disabled'?'false':'true'}),valueInput=new Node({'data-prompt-value':''},'input'),popup=new Node({'data-prompt-popup':''}),attachments=new Node({'data-prompt-attachments':''}),mode=new Node({'data-prompt-mode':''}),status=new Node({'data-prompt-status':''});
 form.dataset={state,mode:'none'};popup.hidden=true;root.append(form);for(const node of [input,valueInput,popup,attachments,mode,status])form.append(node);
 const context=new Node({'data-prompt-open':'context'},'button'),tools=new Node({'data-prompt-open':'tools'},'button'),voice=new Node({'data-prompt-voice':''},'button');for(const button of [context,tools,voice])form.append(button);form.requestSubmit=()=>form.fire('submit');let cleanup;F.wirePromptBar(root,fn=>cleanup=fn);
 return {root,form,input,valueInput,popup,attachments,mode,status,context,tools,voice,cleanup,set(value,start=value.length,end=start){assert.equal(F.setPromptDraft(input,value,{start,end}),true);},choose(action){const button=popup.querySelectorAll('button').find(b=>b.dataset.promptAction===action);assert.ok(button,action);popup.fire('click',{target:button});}};
}
test(()=>{const f=fixture();f.set('Review');assert.equal(f.input.fire('keydown',{key:'Enter',isComposing:true}).defaultPrevented,undefined);f.input.fire('keydown',{key:'Enter',shiftKey:true});assert.equal(f.valueInput.value,'Review\n');f.input.fire('keydown',{key:'Enter'});assert.equal(f.valueInput.value,'');assert.equal(f.status.textContent,'Prompt sent in this preview.');f.set('   ');f.form.fire('submit');assert.equal(f.status.textContent,'Enter a prompt.');assert.equal(f.input.getAttribute('aria-invalid'),'true');f.set('Valid');assert.equal(f.input.getAttribute('aria-invalid'),null);f.cleanup();});
test(()=>{for(const state of ['pending','disabled']){const f=fixture(state);f.input.textContent='Keep this draft';f.input.fire('input');f.input.fire('keydown',{key:'Enter'});f.form.fire('submit');assert.equal(f.valueInput.value,'Keep this draft');if(state==='disabled'){assert.equal(F.setPromptDraft(f.input,'No'),false);f.form.fire('click',{target:f.voice});assert.equal(f.status.textContent,'');}f.cleanup();}});
test(()=>{const f=fixture();f.form.fire('click',{target:f.tools});assert.equal(f.popup.hidden,false);const research=f.popup.querySelectorAll('button').find(b=>b.dataset.promptValue==='research');f.popup.fire('click',{target:research});assert.equal(f.form.dataset.mode,'research');assert.match(f.mode.innerHTML,/Run deep research/);f.form.fire('click',{target:f.context});f.popup.fire('keydown',{key:'End'});assert.equal(document.activeElement,f.popup.querySelectorAll('button').at(-1));f.popup.fire('keydown',{key:'Escape'});assert.equal(document.activeElement,f.context);f.cleanup();});
test(()=>{const f=fixture();f.form.fire('click',{target:f.context});f.choose('attach');assert.equal(f.attachments.children.length,1);f.form.fire('click',{target:f.voice});assert.equal(f.attachments.children.length,1);assert.match(f.status.textContent,/not available in this browser/);f.form.fire('click',{target:f.attachments.children[0].children[0]});assert.equal(f.attachments.hidden,true);f.cleanup();});
test(()=>{const f=fixture();f.set('Check @As');f.input.fire('input');assert.equal(f.popup.hidden,false);f.choose('insert');assert.equal(f.valueInput.value,'Check @AsterGrid ');assert.equal(f.input.querySelectorAll('[data-prompt-mention]').length,1);assert.equal(f.input.querySelector('[data-prompt-mention]').dataset.promptMention,'company');f.set('Review these.');F.setPromptDraft(f.input,'Review these.',{start:7,end:12});f.form.fire('click',{target:f.context});f.choose('lists');f.choose('insert');assert.equal(f.valueInput.value,'Review #Priority review .');assert.equal(f.input.querySelector('[data-prompt-mention]').dataset.promptMention,'list');f.cleanup();});
test(()=>{const f=fixture();f.set('Safe ');f.input.fire('paste',{clipboardData:{getData:type=>type==='text/plain'?'<img onerror=bad>':''}});assert.equal(f.valueInput.value,'Safe <img onerror=bad>');assert.equal(f.input.querySelectorAll('img').length,0);const savedGetSelection=window.getSelection;window.getSelection=undefined;f.form.fire('click',{target:f.context});f.choose('companies');f.choose('insert');assert.equal(f.valueInput.value,'Safe <img onerror=bad>@AsterGrid ');window.getSelection=savedGetSelection;f.cleanup();});
class Recognition{constructor(){Recognition.instances.push(this);}start(){this.started=true;this.onstart?.();}stop(){this.stopped=true;this.onend?.();}abort(){this.aborted=true;}results(...results){this.onresult?.({results:results.map(([transcript,isFinal])=>Object.assign([{transcript}],{isFinal}))});}}Recognition.instances=[];
test(()=>{window.SpeechRecognition=Recognition;const f=fixture();f.set('Compare');f.form.fire('click',{target:f.voice});const r=Recognition.instances.at(-1);assert.equal(r.started,true);assert.equal(r.interimResults,true);assert.equal(r.continuous,true);assert.equal(f.voice.getAttribute('aria-pressed'),'true');assert.equal(f.form.dataset.voiceActive,'true');r.results(['Aster',false]);assert.equal(f.valueInput.value,'Compare Aster');assert.equal(selection.getRangeAt(0).startContainer,f.input,'Live dictation keeps the caret outside its noneditable span');r.results(['AsterGrid',true],['and Northstar',false]);assert.equal(f.valueInput.value,'Compare AsterGrid and Northstar');assert.equal(f.attachments.children.length,0);f.form.fire('click',{target:f.voice});assert.equal(r.stopped,true);assert.equal(f.valueInput.value,'Compare AsterGrid and Northstar');assert.equal(f.voice.getAttribute('aria-pressed'),'false');assert.equal(f.form.dataset.voiceActive,undefined);f.cleanup();delete window.SpeechRecognition;});
test(()=>{window.webkitSpeechRecognition=Recognition;const f=fixture();f.set('Keep');f.form.fire('click',{target:f.voice});const r=Recognition.instances.at(-1);r.results(['the draft',true]);r.onerror({error:'not-allowed'});assert.match(f.status.textContent,/not allowed/);assert.equal(f.valueInput.value,'Keep the draft');assert.equal(r.aborted,true);assert.equal(r.onresult,null);f.cleanup();delete window.webkitSpeechRecognition;});
test(()=>{window.SpeechRecognition=Recognition;const f=fixture();f.set('Keep this selected phrase.',5,24);f.form.fire('click',{target:f.voice});const r=Recognition.instances.at(-1);assert.equal(f.valueInput.value,'Keep this selected phrase.');r.onerror({error:'not-allowed'});assert.equal(f.valueInput.value,'Keep this selected phrase.','Permission denial retains the selected draft');f.set('Still selected',0,5);f.form.fire('click',{target:f.voice});Recognition.instances.at(-1).onerror({error:'no-speech'});assert.equal(f.valueInput.value,'Still selected','No-speech does not delete the selection');f.set('BeforeAfter',6,6);f.form.fire('click',{target:f.voice});const second=Recognition.instances.at(-1);second.results(['the words',false]);assert.equal(f.valueInput.value,'Before the words After','Dictation separates both adjacent words');second.results(['the final words',true]);assert.equal(f.valueInput.value,'Before the final words After');f.cleanup();delete window.SpeechRecognition;});
test(()=>{window.SpeechRecognition=Recognition;const f=fixture();f.form.fire('click',{target:f.voice});const r=Recognition.instances.at(-1);f.popup.showPopover=undefined;f.form.fire('click',{target:f.context});assert.equal(f.popup.parent,document.body);f.cleanup();assert.equal(r.aborted,true);assert.equal(r.onresult,null);assert.equal(f.popup.parent,f.form);assert.equal(f.popup.hidden,true);assert.equal(F.setPromptDraft(f.input,'After disposal'),false);for(const n of [f.form,f.input,f.popup,document,window])assert.equal(Object.values(n.events).reduce((sum,a)=>sum+a.length,0),0);delete window.SpeechRecognition;});
console.log(JSON.stringify({promptBarConfigurations:configurations,interactionContracts:contracts,status:'passed',scope:'source dimensions, rich mention markup/caret/form value, plain-text paste, voice interim/final/error/unsupported and cleanup; simulated DOM only'}));
