/* Semantic/source geometry and rendering checks; no browser or server. */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const dist=path.join(__dirname,'../dist'),ctx={window:{},document:{createElement:()=>({}),getElementById:()=>({}),head:{append(){}}}};vm.createContext(ctx);
for(const file of [...new Set(['tokens.js','hugeicons-icons.js','tag.js','utility-atoms.js','navigation-controls.js','drawer.js','avatar.js','spinner.js','chip.js','switch-motion.js','menus.js','pitch-patterns.js','feedback.js','slider.js','prompt-bar.js','ai-response.js','detail-blocks.js','card-patterns.js','prompt-suggestions.js','catalogue.js','previews.js','command-menu.js','guided-popover.js','tooltip.js','file-upload.js','date-picker.js','source-shell.js','source-workspace.js','source-details.js','source-trace.js','source-chat.js','chat-bubble.js','component-contracts.js'])])vm.runInContext(fs.readFileSync(path.join(dist,file),'utf8'),ctx,{filename:file});
const F=ctx.window.Forma,css=fs.readFileSync(path.join(dist,'source-details.css'),'utf8');let count=0;
for(const variant of F.sourceDetailsVariants)for(const state of ['populated','empty'])for(const open of [false,true]){const c={variant,state,open},html=F.sourceDetails(c);assert.match(html,/data-source-details=/);assert.doesNotMatch(html,/undefined|NaN|\[object Object\]/,variant);for(const id of F.sourceDetailsTokens(c)){assert.ok(F.tokens[id],id);assert.doesNotThrow(()=>F.resolve(id));}const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,variant+' unique IDs');count++;}
const P=F.sourceDetailsParts;
const fileInput={files:[{size:21*1024*1024}],validationMessage:'',setCustomValidity(message){this.validationMessage=message;}};assert.equal(F.validateSourceDetailsFile(fileInput),false);assert.match(fileInput.validationMessage,/20 MB/);fileInput.files=[{size:1024}];assert.equal(F.validateSourceDetailsFile(fileInput),true);assert.equal(fileInput.validationMessage,'','Choosing a valid file recovers the same input after oversize rejection');

assert.equal(P.inline('<img onerror=x>'),'&lt;img onerror=x&gt;');assert.match(P.prose([['First ',{cite:'S1'}],['Second']]),/<p>First .*<p>Second<\/p>/s);assert.doesNotMatch(P.identity('Unsafe',{href:'javascript:alert(1)'}),/javascript:/);
const projection=F.sourceDetails({variant:'tables',tableStyle:'projection'});assert.equal((projection.match(/scope="col"/g)||[]).length,7);assert.match(projection,/Key risk/);assert.match(projection,/data-ai-source-trigger/);assert.match(projection,/role="region" tabindex="0"/);
const sizing=F.sourceDetails({variant:'tables',tableStyle:'sizing'});assert.doesNotMatch(sizing,/<thead>/);assert.equal((sizing.match(/scope="row"/g)||[]).length,2);
const competition=F.sourceDetails({variant:'tables',tableStyle:'competition'});assert.match(competition,/sr-competitor/);assert.match(competition,/Fieldwork/);
const profiles=F.sourceDetails({variant:'profiles',open:true});assert.equal((profiles.match(/<h3>Experience/g)||[]).length,2);assert.equal((profiles.match(/<h3>Education/g)||[]).length,2);assert.match(profiles,/Full-time/);assert.match(profiles,/Part-time/);assert.match(profiles,/Technical/);assert.match(profiles,/href="https:\/\/example.com"/);assert.match(profiles,/40% equity/);
const questions=F.sourceDetails({variant:'questions'});for(const text of ['required','recommended','optional','Red flag','Assessment reasoning','Provisional assessment','Context','Decision impact','What a good answer could include','Potential red flags','2 of 3 answered'])assert.ok(questions.includes(text),text);assert.doesNotMatch(questions,/Priority<\/dt>|Confidence<\/dt>/);assert.match(F.sourceDetails({variant:'questions',status:'pending'}),/0 of 3 answered/);assert.doesNotMatch(F.sourceDetails({variant:'questions',status:'pending'}),/Assessment reasoning|Provisional assessment/,'Pending answers do not expose assessment from hidden sample answers');
const score=F.sourceDetails({variant:'scorecard'});assert.equal((score.match(/<circle /g)||[]).length,6);assert.equal((score.match(/<rect /g)||[]).length,100);for(const text of ['Research signals','Criteria with evidence','Strong','Weak','Research deltas','Post-submit deltas','+2','-1','Verification rate'])assert.ok(score.includes(text),text);
const updates=F.sourceDetails({variant:'updates'});assert.equal((updates.match(/data-update-kind=/g)||[]).length,3);assert.match(updates,/Original question/);assert.match(updates,/sr-change-values/);assert.match(updates,/data-update-filter="research"/);assert.match(updates,/data-report-action="updates-read"/);
const summary=F.sourceDetails({variant:'summary'});for(const text of ['sr-radar-shape','Fund fit','Company &amp; contacts','mailto:alex@example.com','Your decision','sr-breadcrumb','role="tab"','Unread updates'])assert.ok(summary.includes(text),text);
for(const panel of ['files','notes','chat'])assert.doesNotMatch(F.sourceDetails({variant:'panel',panel}),/undefined|NaN/);
for(const panel of ['files','notes']){const html=F.sourceDetails({variant:'panel',panel,state:'empty'});assert.match(html,panel==='notes'?/No notes yet/:/No files have been uploaded/);assert.doesNotMatch(html,/data-file-name=|<details class="sr-note-row"/,'Empty inventory has no sample rows');}const emptyFile=F.sourceDetails({variant:'files',state:'empty'});assert.match(emptyFile,/Original file not attached/);assert.doesNotMatch(emptyFile,/Open original file|<iframe|<pre/);
for(const fileType of ['document','text','pdf','image']){const html=F.sourceDetails({variant:'files',fileType});assert.match(html,/Open original file/);assert.doesNotMatch(html,/https:\/\/example.com/,'File original action must point to the actual fixture');}assert.doesNotMatch(F.sourceDetails({variant:'files',fileType:'unavailable'}),/Open original file/);
for(const c of [{variant:'research'},{variant:'updates'},{variant:'profiles',avatar:'image'},{variant:'application'},{variant:'summary'},{variant:'panel',panel:'chat'},{variant:'panel',panel:'trace'}]){const ids=new Set(F.sourceDetailsTokens(c));for(const [,name]of F.sourceDetails(c).matchAll(/var\(--pp-([\w-]+)/g)){const id=Object.keys(F.tokens).find(id=>id.replace(/\./g,'-')===name);assert.ok(ids.has(id),c.variant+' inspector omits '+id);}}
for(const [,name]of css.matchAll(/var\(--pp-([^),\s]+)/g)){const found=Object.keys(F.tokens).some(id=>id.replace(/\./g,'-')===name);assert.ok(found,'CSS token '+name);}
assert.match(css,/grid-template-columns:1fr 2fr/);assert.match(css,/grid-template-columns:1fr 1\.08fr/);assert.match(css,/@container\(max-width:700px\)/);assert.match(css,/@media\(forced-colors:active\)/);assert.equal(typeof F.wireSourceDetails,'function');
console.log('Source details: '+count+' rendering configurations; rich tables, profiles, Q&A, score, updates, summary and token contracts pass.');
