/* Static renderer contracts + local state and DOM-event harness. No browser/server. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const dist=path.join(__dirname,'../dist');
const emitter=()=>({listeners:new Map(),addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,new Set());this.listeners.get(type).add(fn);},removeEventListener(type,fn){this.listeners.get(type)?.delete(fn);},emit(type,event){for(const fn of this.listeners.get(type)||[])fn(event);}});
const document={...emitter(),getElementById:()=>({}),createElement:()=>({}),head:{append(){}}},window={...emitter(),innerWidth:1000,innerHeight:800};
const context={window,document,setTimeout,clearTimeout};vm.createContext(context);
for(const file of ['tokens.js','hugeicons-icons.js','tag.js','utility-atoms.js','navigation-controls.js','drawer.js','previews.js','command-menu.js','guided-popover.js','tooltip.js','file-upload.js','date-picker.js','avatar.js','source-trace.js'])vm.runInContext(fs.readFileSync(path.join(dist,file),'utf8'),context,{filename:file});
const F=window.Forma,js=fs.readFileSync(path.join(dist,'source-trace.js'),'utf8'),css=fs.readFileSync(path.join(dist,'source-trace.css'),'utf8');
assert.doesNotMatch(css,/\.pp-trace-node-meta \.pp-badge\{[^}]*(?:height|font-size|padding):/,'Trace nodes use unchanged shared badge geometry');
assert.doesNotMatch(css,/\.pp-trace-map \.pp-avatar\{[^}]*(?:width|height|border-radius):/,'Trace company identity uses native small square avatar');
for(const token of ['component.avatar.size.sm','component.avatar.radius.square',...Object.values(F.badgeTokens({tone:'warning',size:'sm'}))])assert.ok(F.sourceTraceTokens({variant:'map'}).includes(token),token);
assert.equal(F.resolve('component.trace.map.companyAvatar'),F.resolve('component.avatar.size.sm'));assert.equal(F.resolve('component.trace.map.companyRadius'),F.resolve('component.avatar.radius.square'));
let configurations=0;
for(const variant of ['sidebar','map','confidence','sources'])for(const confidence of ['high','moderate','low'])for(const expanded of [true,false]){
 const c={variant,confidence,expanded},html=F.sourceTrace(c);assert.match(html,/data-source-trace/);assert.doesNotMatch(html,/\b(?:undefined|null)\b/);
 for(const id of F.sourceTraceTokens(c)){assert.ok(F.tokens[id],id);F.resolve(id);if(id.startsWith('component.trace.'))assert.match(F.tokens[id].value,/^\{[^}]+\}$/);}
 if(variant==='sidebar'){
  assert.equal((html.match(/class="pp-trace-finding-card/g)||[]).length,3);assert.equal((html.match(/class="pp-trace-synthesis-card/g)||[]).length,2);assert.match(html,/class="pp-trace-more"/);assert.match(html,/data-trace-action="evidence-toggle" aria-expanded="true"/);assert.match(html,/3 sources/);assert.match(html,/aria-describedby="trace-\d+-active"/);assert.equal((html.match(/ open>/g)||[]).length,expanded?2:0);assert.match(html,/role="tooltip"/);assert.doesNotMatch(html,/<summary[^>]+role=/);
 }else if(variant==='map'){
  for(const kind of ['company','area','finding','synthesis','signal','source'])assert.match(html,new RegExp('kind-'+kind));assert.equal((html.match(/kind-area/g)||[]).length,6);assert.match(html,/pp-trace-connectors/);assert.match(html,/path class="is-active"/);assert.match(html,/data-trace-action="more"/);assert.match(html,/aria-label="Research canvas\./);assert.match(html,/aria-live="polite"/);assert.match(html,/data-hugeicon="MinusSignIcon"/);assert.match(html,/data-hugeicon="Add01Icon"/);assert.match(html,/rel="noopener noreferrer"/);
 }else if(variant==='confidence'){
  for(const level of ['high','moderate','low'])assert.match(html,new RegExp('data-node="confidence-'+level+'"'));assert.match(html,/not independent verification|not a confirmed negative finding/);assert.match(html,/<line x1="7.09739" y1="0.875"/,'Original PP high-confidence glyph geometry');
 }else{for(const state of ['available','pending','missing'])assert.match(html,new RegExp('pp-trace-source-row '+state));assert.match(html,/Source record available/);assert.match(html,/Review pending/);assert.match(html,/Not attached/);}
 configurations++;
}
for(const sourceState of ['available','pending','missing']){const html=F.sourceTrace({variant:'sources',sourceState});assert.equal((html.match(/class="pp-trace-source-row/g)||[]).length,1);assert.match(html,new RegExp('pp-trace-source-row '+sourceState));configurations++;}
const ids=[...F.sourceTrace({}).matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);const ids2=[...F.sourceTrace({}).matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.some(id=>ids2.includes(id)),false,'Specimens have independent IDs');
const unsafe=F.sourceTrace({variant:'sources',company:'<script>',statement:'<img onerror=x>',sources:[{title:'<unsafe>',url:'javascript:alert(1)',id:'injected',children:['injected'],kind:'company'}]});assert.doesNotMatch(unsafe,/<unsafe>|<script>|<img onerror|href="javascript:/);assert.match(unsafe,/&lt;unsafe&gt;/);
const custom=F.createSourceTraceModel({sources:[{title:'A',url:'https://example.org'},{title:'B',url:'javascript:alert(1)'}]});assert.equal(custom.nodes['team-source-1'].url,'');assert.equal(custom.nodes['team-source-0'].url,'https://example.org');assert.equal(custom.nodes['team-source-0'].kind,'source');
const state=F.createSourceTraceState({});const graph=F.sourceTraceGraph(state);assert.equal(state.path.join('>'),'team>team-finding-0>team-synthesis-0>team-signal-0>team-source-0');assert.ok(graph.width>1000&&graph.height>400);assert.equal(graph.nodes.filter(n=>n.id.startsWith('team-source-')).length,2);
state.more('team-signal-0','source');assert.equal(F.sourceTraceGraph(state).nodes.filter(n=>n.id.startsWith('team-source-')).length,3);state.more('team-signal-0','source');assert.equal(F.sourceTraceGraph(state).nodes.filter(n=>n.id.startsWith('team-source-')).length,2);
state.select('team-finding-2');assert.equal(state.path[1],'team-finding-2');assert.ok(F.sourceTraceGraph(state).nodes.some(n=>n.id==='team-finding-2'),'Selected node remains visible beyond initial two');state.select('product');assert.equal(state.area,'product');assert.match(F.sourceTraceGraph(state).html,/is-collapsed/,'Visited inactive area retains compact columns');state.select('team');assert.equal(state.path[1],'team-finding-2','Area selection restores its last branch');state.select('company');assert.equal(state.path.length,0);assert.equal(F.sourceTraceGraph(state).nodes.length,7,'Overview shows company and six areas');state.select('not-real');assert.equal(state.path.length,0);state.select('team');
state.width=1600;state.height=600;state.scale(100);assert.equal(state.zoom,1.8);state.scale(.001);assert.equal(state.zoom,.4);state.pan(1e6,-1e6,800,480);assert.equal(state.x,760);assert.equal(state.y,-200);state.fit(800,480);assert.equal(state.zoom,.45);assert.equal(state.x,40);
const variables=new Set(Object.keys(F.tokens).map(F.varName));for(const [,id]of css.matchAll(/var\((--pp-[a-zA-Z0-9-]+)/g))assert.ok(variables.has(id),id);assert.doesNotMatch(css,/#[0-9a-f]{3,8}\b/i);assert.match(css,/@container/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/forced-colors/);assert.match(css,/motion-paused/);assert.match(css,/focus-visible/);
assert.match(css,/\.pp-source-trace summary:focus-visible\{outline:0;box-shadow:var\(--pp-component-trace-focus\)\}/,'Custom controls have one shared focus shadow');assert.match(css,/@media\(forced-colors:active\)[\s\S]*outline:2px solid Highlight;outline-offset:2px;box-shadow:none/,'Forced colors replace the shadow with a visible outline');
const sidebarControl=css.match(/\.pp-source-trace \.pp-trace-sidebar-heading>\.pp-button\[style\]\{([^}]+)\}/)?.[1],mapControl=css.match(/\.pp-source-trace \.pp-trace-map-controls>\.pp-button\[style\]\{([^}]+)\}/)?.[1];assert.ok(sidebarControl&&mapControl,'Source button selectors have specificity 0,4,0 above shared .pp-theme .pp-button[style] 0,3,0');assert.match(sidebarControl,/border-radius:var\(--pp-radius-9\)/);assert.match(mapControl,/height:var\(--pp-component-trace-map-controlHeight\)/);assert.match(mapControl,/padding:0 var\(--pp-space-8\)/);assert.doesNotMatch(mapControl,/box-shadow:/,'Normal source geometry must not override the shared focus shadow');assert.equal(F.buttonTokens({variant:'ghost',size:'sm'}).shadow,'shadow.none','Ghost map controls already have the required shadow-free default');assert.match(css,/\.pp-source-trace \.pp-trace-map-controls>\.pp-button\[style\]\.icon-only\{padding:0;width:var\(--pp-component-trace-map-controlHeight\)/);assert.match(js,/host\.append\(dialog\)/,'Native top-layer dialog stays a DOM child of the scoped trace wrapper');
for(const [role,value]of Object.entries({'sidebar.width':'391px','sidebar.branchInset':'12px','confidence.control':'16px','confidence.circle':'15px','sources.width':'260px','sources.padding':'16px','sources.rowHeight':'28px','map.findingWidth':'226px','map.synthesisWidth':'242px','map.signalWidth':'246px','map.sourceWidth':'244px','map.columnGap':'48px'}))assert.equal(F.resolve('component.trace.'+role),value,role);
// Exercise real event closures with minimal element objects; this does not assert layout.
let focused=null;const classes=()=>({values:new Set(),add(x){this.values.add(x);},remove(x){this.values.delete(x);},toggle(x,on){if(on)this.add(x);else this.remove(x);}});
const element=(dataset={})=>({dataset,style:{},classList:classes(),hidden:false,isConnected:true,innerHTML:'',textContent:'',offsetWidth:260,offsetHeight:200,attributes:{},setAttribute(k,v){this.attributes[k]=v;},focus(){focused=this;},matches(){return false;},contains(n){return n===this;},getBoundingClientRect(){return{left:0,top:0,right:800,bottom:480,width:800,height:480};},closest(){return null;},querySelector(){return null;}});
const popup=element(),content=element(),world=element(),canvas=element(),output=element(),crumb=element(),help=element(),staticSources=element(),focusButton=element();popup.hidden=true;help.hidden=true;popup.querySelector=()=>focusButton;staticSources.querySelector=()=>focusButton;canvas.setPointerCapture=()=>{};canvas.hasPointerCapture=()=>true;canvas.releasePointerCapture=()=>{};
const host={...element({traceId:'test-trace',traceConfig:JSON.stringify({variant:'map'}),traceVariant:'map'}),...emitter()};
host.querySelector=selector=>({'[data-trace-content]':content,'[data-trace-popup]':popup,'.pp-trace-canvas':canvas,'.pp-trace-world':world,'.pp-trace-zoom-label':output,'.pp-trace-breadcrumb':crumb,'.pp-trace-map-help':help,'.pp-trace-sources-static':staticSources}[selector]||focusButton);
host.append=()=>{};const dialogs=[];document.createElement=tag=>{assert.equal(tag,'dialog');const d={...element(),...emitter(),open:false,append(){},remove(){this.removed=true;},showModal(){this.open=true;},close(){this.open=false;this.emit('close',{});},querySelector:host.querySelector};dialogs.push(d);return d;};
const cleanup=[];F.wireSourceTrace({querySelectorAll:()=>[host]},fn=>cleanup.push(fn));assert.match(world.style.transform,/scale\(/);assert.ok(host.listeners.size>=10);F.wireSourceTrace({querySelectorAll:()=>[host]},fn=>cleanup.push(fn));assert.equal(cleanup.length,1,'Repeated wiring is idempotent');
const targetFor=(b,kind='action')=>({closest(selector){if(selector==='[data-trace-pop]'&&kind==='pop')return b;if(selector==='[data-trace-action]'&&kind==='action')return b;return null;}});
const pop=element({tracePop:'trust',node:'confidence-high'});host.emit('click',{target:targetFor(pop,'pop')});assert.equal(popup.hidden,false);assert.match(popup.innerHTML,/High/);assert.equal(pop.attributes['aria-expanded'],'true');
let prevented=0;host.emit('keydown',{key:'Escape',target:pop,preventDefault(){prevented++;},stopPropagation(){}});assert.equal(popup.hidden,true);assert.equal(focused,pop);assert.equal(pop.attributes['aria-expanded'],'false');assert.equal(prevented,1);
const sources=element({tracePop:'sources',node:'team-signal-0'});host.emit('click',{target:targetFor(sources,'pop')});assert.match(popup.innerHTML,/pp-trace-source-row pending/);const source=element({traceAction:'source',node:'team-source-0'});source.closest=selector=>selector==='[data-trace-popup]'?popup:null;host.emit('click',{target:targetFor(source)});assert.match(popup.innerHTML,/Open original/);assert.equal(focused,focusButton);const back=element({traceAction:'source-back'});back.closest=source.closest;host.emit('click',{target:targetFor(back)});assert.match(popup.innerHTML,/pp-trace-source-row/);
const list=element();const group={querySelector:()=>list};const toggle=element({traceAction:'evidence-toggle'});toggle.closest=()=>group;host.emit('click',{target:targetFor(toggle)});assert.equal(list.hidden,true);assert.equal(toggle.attributes['aria-expanded'],'false');host.emit('click',{target:targetFor(toggle)});assert.equal(list.hidden,false);
const click=(action,id,kind)=>{const b=element({traceAction:action,node:id,kind});host.emit('click',{target:targetFor(b)});return b;};click('more','team-signal-0','source');assert.match(world.innerHTML,/team-source-2/);click('node','product');assert.match(crumb.innerHTML,/>Product</);click('definition',null,'signal');assert.equal(help.hidden,false);assert.match(help.innerHTML,/observation or open question/);
canvas.closest=selector=>selector==='.pp-trace-canvas'?canvas:null;const before=world.style.transform;host.emit('keydown',{key:'ArrowLeft',target:canvas,preventDefault(){prevented++;}});assert.notEqual(world.style.transform,before);const zoomBefore=output.textContent;host.emit('keydown',{key:'+',target:canvas,preventDefault(){}});assert.notEqual(output.textContent,zoomBefore);host.emit('keydown',{key:'0',target:canvas,preventDefault(){}});
host.emit('pointerdown',{target:canvas,button:0,pointerId:1,clientX:0,clientY:0});assert.equal(canvas.classList.values.has('is-dragging'),true);host.emit('pointermove',{clientX:10,clientY:15});host.emit('pointerup',{});assert.equal(canvas.classList.values.has('is-dragging'),false);host.emit('wheel',{target:canvas,deltaX:10,deltaY:20,ctrlKey:false,preventDefault(){prevented++;}});
const modalOpener=click('map-expand');assert.equal(dialogs.length,1);assert.equal(dialogs[0].open,true);assert.match(dialogs[0].innerHTML,/data-trace-action="map-close"/);assert.equal(dialogs[0].attributes['aria-label'],'AsterGrid research map');click('map-expand');assert.equal(dialogs.length,1,'Opening an active map does not duplicate its dialog');click('map-close');assert.equal(dialogs[0].removed,true);assert.equal(focused,modalOpener);click('map-expand');dialogs[1].emit('cancel',{preventDefault(){}});assert.equal(dialogs[1].removed,true);click('map-expand');host.emit('click',{target:dialogs[2]});assert.equal(dialogs[2].removed,true,'Backdrop click closes the modal');click('map-expand');
host.matches=selector=>selector==='[data-source-trace]';F.disposeSourceTrace(host);F.disposeSourceTrace(host);cleanup[0]();assert.equal(dialogs[3].removed,true,'Disposal removes an active native modal');assert.equal(dialogs.every(d=>[...d.listeners.values()].every(s=>s.size===0)),true);assert.equal([...host.listeners.values()].reduce((n,s)=>n+s.size,0),0);assert.equal([...document.listeners.values()].reduce((n,s)=>n+s.size,0),0);assert.equal([...window.listeners.values()].reduce((n,s)=>n+s.size,0),0);assert.equal(host.dataset.traceWired,undefined);assert.equal(popup.hidden,true);F.wireSourceTrace(host,fn=>cleanup.push(fn));assert.equal(host.dataset.traceWired,'true','A wrapper itself can be wired after disposal');F.disposeSourceTrace(host);
assert.doesNotMatch(js,/fetch\(|localStorage|location\.(?:href|hash)\s*=/,'No backend or app navigation is claimed by the local sample');
console.log(JSON.stringify({configurations,sourcePatterns:23,interactionContracts:23,status:'passed',limitations:'Static geometry and event contracts only; no browser appearance or assistive-technology verification.'}));
