/* Source chat composition contracts and scoped interactions; no browser or service. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const dist=path.join(__dirname,'../dist'),doc={createElement:()=>({}),getElementById:()=>({}),head:{append(){}}};
const ctx={window:{},document:doc,Intl,URLSearchParams,CustomEvent:class{constructor(type,options={}){this.type=type;Object.assign(this,options);}}};vm.createContext(ctx);
for(const file of ['tokens.js','hugeicons-icons.js','tag.js','utility-atoms.js','navigation-controls.js','drawer.js','avatar.js','spinner.js','chip.js','menus.js','pitch-patterns.js','feedback.js','layout-system.js','slider.js','prompt-bar.js','ai-response.js','detail-blocks.js','card-patterns.js','catalogue.js','previews.js','command-menu.js','guided-popover.js','tooltip.js','file-upload.js','date-picker.js','source-workspace.js','source-chat.js','chat-bubble.js'])vm.runInContext(fs.readFileSync(path.join(dist,file),'utf8'),ctx,{filename:file});
const F=ctx.window.Forma,css=fs.readFileSync(path.join(dist,'source-chat.css'),'utf8'),ids=new Set();let configurations=0;
// Existing shared source helpers remain usable, while the public page is bubble-only.
const bubbleItem=F.byId.conversation,bubbleDefaults=F.defaults(bubbleItem);
assert.equal(bubbleItem.name,'Chat bubble');
assert.match(F.preview(bubbleItem,bubbleDefaults),/data-slot="bubble"/);
assert.doesNotMatch(F.preview(bubbleItem,bubbleDefaults),/<(?:table|form|textarea|nav|header|aside)\b|data-source-chat|data-prompt-bar/);
assert.equal(F.componentParts(bubbleItem,bubbleDefaults).length,0);
for(const section of ['types','states','overview']){
 const migrated=F.migrateRoute('conversation',section,'variant=conversation&state=thinking&response=table&metadata=true&chart=true&appearance=outline&align=start&grouping=grouped');
 assert.equal(migrated.id,'conversation');assert.equal(migrated.section,'overview');
 assert.equal(migrated.query,'appearance=outline&align=start&grouping=grouped');
}
assert.equal(F.migrateRoute('conversation','groups','grouping=grouped').section,'groups');
for(const variant of F.sourceChatVariants)for(const state of ['complete','thinking'])for(const metadata of [false,true]){
 const c={variant,state,metadata},html=F.sourceChat(c);
 assert.ok(html.includes(`data-source-chat="${variant}"`));assert.doesNotMatch(html,/undefined|NaN|Infinity/);
 for(const [,id]of html.matchAll(/\bid="([^"]+)"/g)){assert.ok(!ids.has(id),`Duplicate ${id}`);ids.add(id);}
 for(const token of F.sourceChatTokens(c)){assert.ok(F.tokens[token],`${variant}: ${token}`);F.resolve(token);}
 if(variant==='conversation'){assert.match(html,/data-prompt-bar/);assert.match(html,/pp-ai-response/);assert.match(html,/data-chat-result|pp-chat-result-save/);}
 if(variant==='message'){assert.match(html,/<article[^>]*aria-label="Your message"/);assert.equal(html.includes('Company overview.pdf'),metadata);}
 if(variant==='company-panel'){assert.match(html,/<textarea[^>]*name="prompt"[^>]*required/);assert.ok(/<button[^>]*type="submit"[^>]*data-chat-compact-send/.test(html));assert.equal(html.includes('pp-chat-growth-bars'),state==='complete');}
 if(variant==='save-list'){assert.match(html,/data-sw-form="save-list"/);assert.match(html,/data-chat-save-kind="existing"/);}
 configurations++;
}
assert.match(F.sourceChat({variant:'save-list',allowDynamic:false,selectedCount:0}),/data-chat-save-kind="static" disabled/);
assert.match(F.sourceChat({variant:'save-list',allowDynamic:false}),/data-chat-save-kind="dynamic" disabled/);
assert.match(F.sourceChat({variant:'history',history:[]}),/No conversations yet/);
assert.match(F.sourceChat({variant:'history',query:'zzzz'}),/No conversations found/);
assert.deepEqual(Array.from(F.filterChatHistory([{title:'Revenue',terms:'AsterGrid'},{title:'Team',terms:'Founders'}],'ASTER')).map(x=>x.title),['Revenue']);
const unsafe=F.sourceChat({variant:'history',title:'<img src=x>',history:[{id:'"><svg>',title:'</script><img onerror=1>',terms:'a'}]});assert.doesNotMatch(unsafe,/<img|<svg>.*script|<\/script><img/);assert.match(unsafe,/\\u003c\/script/);
assert.equal(F.resolve('component.sourceChat.bubble.radius'),'9px');assert.equal(F.resolve('component.sourceChat.panel.width'),'391px');assert.equal(F.resolve('component.sourceChat.history.width'),'320px');
for(const [,name]of css.matchAll(/var\((--pp-[\w-]+)/g))assert.ok(Object.keys(F.tokens).some(id=>F.varName(id)===name),name);
assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/body\.motion-paused/);assert.match(css,/@container\(max-width:480px\)/);
for(const key of ['clock','down','search','settings','file','plus','grid','bolt','chevron','chat','arrow'])assert.ok(F.icons[key],`No fallback glyph for ${key}`);
// Minimal DOM harness executes actual handlers, including repeated wire/dispose behavior.
class Node{
 constructor(){this.map=new Map;this.lists=new Map;this.listeners=new Map;this.dataset={};this.attrs={};this.hidden=false;this.value='';this.textContent='';this.style={};this.isConnected=true;this.classList={contains:()=>false};}
 addEventListener(type,fn){const a=this.listeners.get(type)||[];a.push(fn);this.listeners.set(type,a);}removeEventListener(type,fn){this.listeners.set(type,(this.listeners.get(type)||[]).filter(x=>x!==fn));}
 querySelector(s){return this.map.get(s)||null;}querySelectorAll(s){return this.lists.get(s)||[];}set(s,n){this.map.set(s,n);return n;}list(s,n){this.lists.set(s,n);return n;}
 setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}matches(s){return s==='[data-source-chat]'?!!this.isHost:s===':popover-open'?!!this.open:false;}
 contains(n){return n===this||[...this.map.values()].includes(n);}closest(s){return this.closestMap?.[s]||null;}focus(){this.focused=true;}getBoundingClientRect(){return {left:990,bottom:750,width:80,height:40};}
 showPopover(){this.open=true;}hidePopover(){this.open=false;}dispatchEvent(event){(this.events??=[]).push(event);return true;}fire(type,event={}){for(const fn of [...this.listeners.get(type)||[]])fn({target:this,preventDefault(){this.prevented=true;},...event});}
 listenerCount(){return [...this.listeners.values()].reduce((n,a)=>n+a.length,0);}
}
const view=new Node;view.innerWidth=1024;view.innerHeight=768;const documentNode=new Node;documentNode.defaultView=view;documentNode.body=new Node;
const host=new Node;host.isHost=true;host.ownerDocument=documentNode;const status=host.set('[data-chat-status]',new Node),trigger=new Node,pop=new Node,input=new Node,results=new Node,title=host.set('[data-chat-current-title]',new Node),data=new Node;data.textContent=JSON.stringify([{id:'a',title:'Energy opportunities',terms:'AsterGrid'},{id:'b',title:'Team review',terms:'founders'}]);trigger.attrs['aria-controls']='history';pop.offsetWidth=320;pop.offsetHeight=200;pop.set('input,button',input);pop.set('[data-chat-history-search]',input);pop.set('[data-chat-history-results]',results);pop.set('[data-chat-history-data]',data);host.set('#history',pop);host.set('[data-chat-popup]',pop);host.list('[data-chat-popup-trigger]',[trigger]);host.list('[data-chat-popup]',[pop]);host.list('[data-chat-history-popup]',[pop]);
let dispose;F.wireSourceChat(host,fn=>dispose=fn);const count=trigger.listenerCount();F.wireSourceChat(host);assert.equal(trigger.listenerCount(),count,'Wiring a nested wrapper twice adds no duplicate listener');
trigger.fire('click');assert.equal(pop.hidden,false);assert.equal(trigger.attrs['aria-expanded'],'true');assert.equal(pop.style.left,'696px');assert.equal(pop.style.top,'560px');assert.ok(input.focused);
input.value='founders';input.fire('input');assert.match(results.innerHTML,/Team review/);assert.doesNotMatch(results.innerHTML,/Energy opportunities/);input.value='notfound';input.fire('input');assert.match(results.innerHTML,/No conversations found/);
const selection=new Node;selection.dataset.chatHistorySelect='b';selection.closestMap={'[data-chat-history-select]':selection};results.fire('click',{target:selection});assert.equal(title.textContent,'Team review');assert.equal(host.events.at(-1).type,'forma:conversation-select');assert.equal(pop.hidden,true);assert.ok(trigger.focused);
trigger.fire('click');documentNode.fire('keydown',{key:'Escape'});assert.equal(pop.hidden,true);dispose();assert.equal(trigger.listenerCount(),0);assert.equal(documentNode.listenerCount(),0);assert.equal(view.listenerCount(),0);dispose();
// Compact composer sends only nonempty text, keeps Shift+Enter/IME and clears local files.
const compact=new Node;compact.isHost=true;compact.ownerDocument=documentNode;const form=compact.set('[data-chat-compact-compose]',new Node),textarea=form.set('textarea',new Node),file=form.set('[data-chat-file]',new Node),name=form.set('[data-chat-file-name]',new Node),messages=compact.set('[data-chat-messages]',new Node),compactStatus=compact.set('[data-chat-status]',new Node);textarea.setCustomValidity=x=>textarea.error=x;textarea.reportValidity=()=>textarea.reported=true;file.files=[{name:'Overview.pdf'}];messages.insertAdjacentHTML=(position,html)=>messages.html=(messages.html||'')+html;
let disposeCompact;F.wireSourceChat(compact,fn=>disposeCompact=fn);textarea.value='   ';form.fire('submit');assert.ok(textarea.error);assert.equal(messages.html,undefined);textarea.value='A < B';textarea.fire('input');assert.equal(textarea.error,'');textarea.fire('keydown',{key:'Enter',shiftKey:true});assert.equal(messages.html,undefined);textarea.fire('keydown',{key:'Enter',isComposing:true});assert.equal(messages.html,undefined);textarea.fire('keydown',{key:'Enter'});assert.match(messages.html,/A &lt; B/);assert.match(messages.html,/Overview.pdf/);assert.equal(textarea.value,'');assert.equal(compact.events.at(-1).type,'forma:conversation-send');assert.match(compactStatus.textContent,/No AI service/);textarea.disabled=true;textarea.value='Do not send';form.fire('submit');assert.doesNotMatch(messages.html,/Do not send/);disposeCompact();assert.equal(textarea.listenerCount(),0);assert.equal(form.listenerCount(),0);
// Source Save List entry reuses workspace bodies and returns focus after dialog close.
const saveHost=new Node;saveHost.isHost=true;saveHost.ownerDocument=documentNode;const save=new Node,savePop=new Node,saveTrigger=new Node,choices=new Node,membership=new Node,back=new Node,dialog=new Node,closer=new Node,staticForm=new Node,dynamicForm=new Node,dialogInput=new Node;
staticForm.dataset.chatSaveForm='static';dynamicForm.dataset.chatSaveForm='dynamic';dialog.list('[data-chat-save-form]',[staticForm,dynamicForm]);dialog.set('[data-chat-save-form]:not([hidden]) input',dialogInput);dialog.showModal=()=>dialog.open=true;dialog.close=()=>{dialog.open=false;dialog.fire('close');};save.set('[data-chat-popup]',savePop);save.set('[data-chat-save-choices]',choices);save.set('[data-chat-save-membership]',membership);save.set('[data-chat-save-dialog]',dialog);save.set('[data-chat-save-back]',back);save.set('[data-chat-dialog-close]',closer);save.set('[data-chat-popup-trigger]',saveTrigger);membership.set('input,button',new Node);choices.set('button:not(:disabled)',new Node);saveHost.list('[data-chat-save]',[save]);saveHost.set('[data-chat-status]',new Node);
let disposeSave;F.wireSourceChat(saveHost,fn=>disposeSave=fn);const choose=kind=>{const button=new Node;button.dataset.chatSaveKind=kind;button.closestMap={'[data-chat-save-kind]':button};save.fire('click',{target:button});};choose('existing');assert.equal(choices.hidden,true);assert.equal(membership.hidden,false);back.fire('click');assert.equal(choices.hidden,false);assert.equal(membership.hidden,true);choose('dynamic');assert.equal(dialog.open,true);assert.equal(staticForm.hidden,true);assert.equal(dynamicForm.hidden,false);assert.ok(dialogInput.focused);dialog.fire('forma:collection-save',{detail:{name:'New view'}});assert.equal(dialog.open,false);assert.ok(saveTrigger.focused);disposeSave();assert.equal(save.listenerCount(),0);assert.equal(dialog.listenerCount(),0);
// Table sort/load-more motion is bounded, stops on pause/reduced motion, and disposes.
const media=new Node;media.matches=false;view.matchMedia=()=>media;const observers=[];view.MutationObserver=class{constructor(fn){this.fn=fn;observers.push(this);}observe(){}disconnect(){this.disconnected=true;}};
const motionHost=new Node;motionHost.isHost=true;motionHost.ownerDocument=documentNode;const motionTable=new Node,row=new Node,enterRow=new Node;row.dataset={previousIndex:'5',currentIndex:'0'};enterRow.dataset={previousIndex:'-1',currentIndex:'1'};const motion=[];
for(const node of [row,enterRow])node.animate=(frames,options)=>{const a={frames,options,finish(){this.finished=true;},cancel(){this.cancelled=true;}};motion.push(a);return a;};motionTable.list('[data-previous-index]',[row,enterRow]);let disposeMotion;F.wireSourceChat(motionHost,fn=>disposeMotion=fn);motionHost.fire('forma:table-change',{target:motionTable});assert.equal(motion.length,2);assert.equal(motion[0].frames[0].transform,'translateY(120px)');assert.equal(motion[0].options.duration,240);media.matches=true;media.fire('change');assert.ok(motion.every(a=>a.finished&&a.cancelled));motionHost.fire('forma:table-change',{target:motionTable});assert.equal(motion.length,2);media.matches=false;documentNode.body.classList.contains=()=>true;motionHost.fire('forma:table-change',{target:motionTable});assert.equal(motion.length,2);disposeMotion();assert.equal(media.listenerCount(),0);assert.ok(observers.at(-1).disconnected);documentNode.body.classList.contains=()=>false;
assert.match(css,/\.pp-chat-history-search input:focus-visible,\.pp-chat-compact-compose textarea:focus-visible\{outline:0!important;box-shadow:none!important\}/,'Only the compound surface draws focus, despite generic native-input specificity');
assert.match(css,/\.pp-chat-compact-compose>div:has\(textarea:focus-visible\)/,'Send and attachment buttons retain their own indicator without a second composer ring');
console.log(JSON.stringify({configurations,uniqueIds:ids.size,history:'search, selection, clamp, Escape and repeated cleanup',compact:'validation, text escaping, IME, Shift+Enter, files and disabled',save:'membership switch, naming form and focus return',motion:'bounded row entry/reorder, pause/reduced-motion and cleanup',scope:'static and simulated event contracts; no browser',status:'passed'}));
